### ISSUE TITLE
[synthetic-shadow]Invoking dispatchEvent on nodes rendered by the template doesn't respect retargetting

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#1129]
### Description

The synthetic shadow doesn't patch `EventTarget.prototype.dispatchEvent` on the nodes rendered by the template. Because of this the dispatched event `target` property is not properly retargeted when traversing the shadow trees.

Example: https://playground.lwcjs.org/projects/RFCYpTRrS/2/edit

```html
<template>
  <div></div>
</template>
```

```js
const elm = createElement('x-foo', { is: Foo });
document.body.appendChild(elm);

const evt = new CustomEvent('test', { composed: true, bubble: true });

elm.shadowRoot.querySelector('div').dispatchEvent(evt);
console.log(evt.target);
```

#### Expected Results
```
<x-foo>
```

#### Actual Results
```
<div>
```

### Browsers Affected
All

### Version
- LWC: 0.37.0

**Comment by caridy** [comment]
I believe this is fixed now in synthetic-shadow.

@pmdartus can you confirm? in fact, your PR https://github.com/salesforce/lwc/pull/1114 references to many bugs, that they were not merged when that PR was merged, not sure if that was intentionally or not, can you help?

**Comment by ravijayaramappa** [comment]
GUS work item: W-5979455

**Comment by ravijayaramappa** [comment]
Update(1/15/2020): This issue still exists. In the synthetic-shadow, events appear patched only when accessed inside a listener. If the event's reference is retained and accessed outside of a listener, the event appears unpatched. 
Possible solutions include, patching the global Event.prototype or patching EventTarget.prototype.dispatchEvent.

**Comment by caridy** [comment]
This is supposed to be solved by https://github.com/salesforce/lwc/pull/1569, isn't it?

**Comment by ravijayaramappa** [comment]
Yes.

**Comment by ekashida** [comment]
https://github.com/salesforce/lwc/issues/2121
