### ISSUE TITLE
Node.children in test mode doesn't respect the shadowDOM semantic

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#977]
### Description

In `test` mode only accessing `children` on the host element will return the shadow root children, instead of returning an empty array.

```js
const elm = createElement('x-test', { is: Test });
document.body.appendChild(elm);

console(elm.children);
// Actual: [...shadow root children]
// Expected: []
```

This issue is only reproducible in `test` mode because we have a fork in the `children` logic: https://github.com/salesforce/lwc/blob/6e2817f2f6696968f1f8eb2770cea110b1748315/packages/%40lwc/engine/src/faux-shadow/custom-element.ts#L115-L117

### Version
- LWC: 0.35.1

**Comment by caridy** [comment]
this was fixed when creating the synthetic-shadow pkg.

**Comment by ravijayaramappa** [comment]
@caridy We still have the same forking logic for children getter in the synthetic-shadow pkg(https://github.com/salesforce/lwc/blob/master/packages/@lwc/synthetic-shadow/src/faux-shadow/element.ts#L201-L203). Now that jest has been moved off to synthetic shadow, can we remove that snippet from element.ts?
```
    // We cannot patch `children` in test mode
    // because JSDOM uses children for its "native"
    // querySelector implementation. If we patch this,
    // HTMLElement.prototype.querySelector.call(element) will not
    // return any elements from shadow, which is not what we want
    if (process.env.NODE_ENV === 'test') {
        return childrenGetter.call(this);
    }
```

**Comment by caridy** [comment]
yes @ravijayaramappa that's dead code... let's remove it. please, check if there is anything else for test env.
